version: '3.7'

services:
  frontend-server:
    build:
      context: ./client_express
      dockerfile: Dockerfile.dev
    depends_on:
      - backend-server
    ports:
      - 3001:3000

  backend-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
    - 5433:5432